title: Seager
subtitle: The portfolio
description: >- # this means to ignore newlines until "baseurl:"
  I made it happen.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profilekoi.png
author: Divaldo Barros
author_bio: Web developer? An anime addict? A video game enthusiast? A music curator? Just a jack of all trades. Born and raised in Angola, this man challenged the virtual world, and wants to conquer it, no matter what. 
author_email: "di.pabarros@gmail.com"
author_location: Portugal
author_website_url: "seager21.github.io"
typewrite-text: A Jack of many talents. Fullstack developer, Web developer, Fitness Coach, Record Producer. 
hero_cover_img: coverino.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Winprovit
              company_logo: winprovit.png
              company_url: https://www.winprovit.pt
              designation: IT Specialist
              description: Worked as a service desk tecnician.
              visibility: true
            - company_name: Informantem (now Bravantic)
              company_logo: informantem.png
              company_url: https://bravantic.com
              designation: Front End Developer
              description: Worked as a Junior Web Developer, managed multiple web projects, and company & client's websites.
              visibility: true
            - company_name: IntelliOffice
              company_logo: intelioffice.png
              company_url: https://www.winprovit.pt
              designation: Junior Web Development
              description: Worked as a junior web developer.
              visibility: true
            - company_name: Freelancer
              company_logo: microsoft.png
              company_url: https://www.instagram.com/the.karpa
              designation: Freelance Full Stack Developer
              description: Worked/Still Working as a freelance web developer, mobile and web app developer.
              visibility: true

# Education
author_education_details:
              - college_logo: iade.png
                college_name: IADE - Creative University
                college_url: https://www.iade.europeia.pt
                college_degree: Computer Engineering
                description: Bachelor in IT Management
                visibility: true
                - college_logo: europeia.png
                college_name: Universidade Europeia
                college_url: https://www.europeia.pt
                college_degree: Information, Systems, Technology and Programming
                description: Techical Specialization Course
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: logo_monfort.png
                project_title: Monfort By JC
                project_description: An e-commerce website, focused on selling streetwear and accessories.
                project_url: https://monfortbyjc.com
                visibility: true
              - project_thumbnail: kubinga.png
                project_title: Kubinga Landing Page
                project_description: Landing page for a plaform for booking taxis and tracking.
                project_url: https://kubinga.com
                visibility: true
                - project_thumbnail: password.png
                project_title: Password Generator
                project_description: A web app that generates 8, 12, 24, 36-digit passwords.
                visibility: true
                - project_thumbnail: mercadobrpt.png
                project_title: Mercado Brasil Portugal (now Mais Brasil Mercado)
                project_description: An e-commerce website, focused on selling brazilian consumables in Portugal.
                project_url: https://maisbrasilmercado.com/
                visibility: true
                - project_thumbnail: activity.png
                project_title: User Activity Tracker App
                project_description: A web application that tracks user activity, logs, alterations.
                visibility: true
                - project_thumbnail: ebook.png
                project_title: E-Book Storage
                project_description: An E-book storage website that stores university PDF e-books, using cloud computing and storage
                visibility: true

# social links
twitter_username: divaldo_barros
github_username:  seager21
instagram_username: stepfatherkoi
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: seager21

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: di.pabarros@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: karpa
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
